[
  "<ignored>",
  {
    "ignores": [
      "**/node_modules",
      "**/dist",
      "**/.dist",
      "**/coverage",
      "**/build",
      "**/.git",
      "**/.cache",
      "**/.nuxt",
      "**/.next",
      "**/.vercel",
      "**/.changeset",
      "**/.idea",
      "**/.output",
      "**/.vitepress/cache",
      "**/.vscode",
      "**/__snapshots__",
      "**/package-lock.json",
      "**/yarn.lock",
      "**/pnpm-lock.yaml",
      "**/bun.lockb",
      "**/CHANGELOG*.md",
      "**/*.min.*",
      "**/LICENSE*",
      "**/__fixtures__",
      "**/fixtures/**",
    ],
    "name": "globalIgnores 5",
  },
  "<ignored>",
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "opencover/javascript/rules",
    "rules": [
      "constructor-super",
      "for-direction",
      "getter-return",
      "no-async-promise-executor",
      "no-case-declarations",
      "no-class-assign",
      "no-compare-neg-zero",
      "no-cond-assign",
      "no-const-assign",
      "no-constant-binary-expression",
      "no-constant-condition",
      "no-control-regex",
      "no-debugger",
      "no-delete-var",
      "no-dupe-args",
      "no-dupe-class-members",
      "no-dupe-else-if",
      "no-dupe-keys",
      "no-duplicate-case",
      "no-empty",
      "no-empty-character-class",
      "no-empty-pattern",
      "no-empty-static-block",
      "no-ex-assign",
      "no-extra-boolean-cast",
      "no-fallthrough",
      "no-func-assign",
      "no-global-assign",
      "no-import-assign",
      "no-invalid-regexp",
      "no-irregular-whitespace",
      "no-loss-of-precision",
      "no-misleading-character-class",
      "no-new-native-nonconstructor",
      "no-nonoctal-decimal-escape",
      "no-obj-calls",
      "no-octal",
      "no-prototype-builtins",
      "no-redeclare",
      "no-regex-spaces",
      "no-self-assign",
      "no-setter-return",
      "no-shadow-restricted-names",
      "no-sparse-arrays",
      "no-this-before-super",
      "no-undef",
      "no-unexpected-multiline",
      "no-unreachable",
      "no-unsafe-finally",
      "no-unsafe-negation",
      "no-unsafe-optional-chaining",
      "no-unused-labels",
      "no-unused-private-class-members",
      "no-unused-vars",
      "no-useless-backreference",
      "no-useless-catch",
      "no-useless-escape",
      "no-with",
      "require-yield",
      "use-isnan",
      "valid-typeof",
      "block-spacing",
      "capitalized-comments",
      "comma-spacing",
      "key-spacing",
      "keyword-spacing",
      "no-console",
      "no-multi-spaces",
      "no-multiple-empty-lines",
      "no-restricted-syntax",
      "no-unneeded-ternary",
      "no-use-before-define",
      "object-curly-spacing",
      "quote-props",
      "quotes",
      "semi",
      "space-before-blocks",
      "space-in-parens",
      "space-infix-ops",
      "spaced-comment",
      "lines-between-class-members",
    ],
  },
  {
    "name": "opencover/typescript/setup",
    "plugins": [
      "@typescript-eslint",
    ],
  },
  {
    "files": [
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "languageOptions": {
      "parser": "typescript-eslint/parser",
      "parserOptions": {
        "ecmaVersion": 2024,
        "sourceType": "module",
      },
    },
    "name": "opencover/typescript/parser",
  },
  {
    "files": [
      "**/*.?([cm])ts",
      "**/*.?([cm])tsx",
    ],
    "name": "opencover/typescript/rules",
    "rules": [
      "- constructor-super",
      "- getter-return",
      "- no-class-assign",
      "- no-const-assign",
      "- no-dupe-args",
      "- no-dupe-class-members",
      "- no-dupe-keys",
      "- no-func-assign",
      "- no-import-assign",
      "- no-new-native-nonconstructor",
      "- no-new-symbol",
      "- no-obj-calls",
      "- no-redeclare",
      "- no-setter-return",
      "- no-this-before-super",
      "- no-undef",
      "- no-unreachable",
      "- no-unsafe-negation",
      "no-var",
      "- no-with",
      "prefer-const",
      "prefer-rest-params",
      "prefer-spread",
      "@typescript-eslint/ban-ts-comment",
      "- no-array-constructor",
      "@typescript-eslint/no-array-constructor",
      "@typescript-eslint/no-duplicate-enum-values",
      "@typescript-eslint/no-empty-object-type",
      "@typescript-eslint/no-explicit-any",
      "@typescript-eslint/no-extra-non-null-assertion",
      "@typescript-eslint/no-misused-new",
      "@typescript-eslint/no-namespace",
      "@typescript-eslint/no-non-null-asserted-optional-chain",
      "@typescript-eslint/no-require-imports",
      "@typescript-eslint/no-this-alias",
      "@typescript-eslint/no-unnecessary-type-constraint",
      "@typescript-eslint/no-unsafe-declaration-merging",
      "@typescript-eslint/no-unsafe-function-type",
      "- no-unused-expressions",
      "@typescript-eslint/no-unused-expressions",
      "- no-unused-vars",
      "@typescript-eslint/no-unused-vars",
      "@typescript-eslint/no-wrapper-object-types",
      "@typescript-eslint/prefer-as-const",
      "@typescript-eslint/prefer-namespace-keyword",
      "@typescript-eslint/triple-slash-reference",
      "@typescript-eslint/await-thenable",
      "@typescript-eslint/no-array-delete",
      "@typescript-eslint/no-base-to-string",
      "@typescript-eslint/no-duplicate-type-constituents",
      "@typescript-eslint/no-floating-promises",
      "@typescript-eslint/no-for-in-array",
      "- no-implied-eval",
      "@typescript-eslint/no-implied-eval",
      "@typescript-eslint/no-misused-promises",
      "@typescript-eslint/no-redundant-type-constituents",
      "@typescript-eslint/no-unnecessary-type-assertion",
      "@typescript-eslint/no-unsafe-argument",
      "@typescript-eslint/no-unsafe-assignment",
      "@typescript-eslint/no-unsafe-call",
      "@typescript-eslint/no-unsafe-enum-comparison",
      "@typescript-eslint/no-unsafe-member-access",
      "@typescript-eslint/no-unsafe-return",
      "@typescript-eslint/no-unsafe-unary-minus",
      "- no-throw-literal",
      "@typescript-eslint/only-throw-error",
      "- prefer-promise-reject-errors",
      "@typescript-eslint/prefer-promise-reject-errors",
      "- require-await",
      "@typescript-eslint/require-await",
      "@typescript-eslint/restrict-plus-operands",
      "@typescript-eslint/restrict-template-expressions",
      "@typescript-eslint/unbound-method",
      "@typescript-eslint/no-confusing-void-expression",
      "@typescript-eslint/no-deprecated",
      "@typescript-eslint/no-meaningless-void-operator",
      "@typescript-eslint/no-misused-spread",
      "@typescript-eslint/no-mixed-enums",
      "@typescript-eslint/no-unnecessary-boolean-literal-compare",
      "@typescript-eslint/no-unnecessary-condition",
      "@typescript-eslint/no-unnecessary-template-expression",
      "@typescript-eslint/no-unnecessary-type-arguments",
      "@typescript-eslint/no-unnecessary-type-conversion",
      "@typescript-eslint/no-unnecessary-type-parameters",
      "@typescript-eslint/no-useless-default-assignment",
      "@typescript-eslint/prefer-reduce-type-parameter",
      "@typescript-eslint/prefer-return-this-type",
      "@typescript-eslint/related-getter-setter-pairs",
      "- no-return-await",
      "@typescript-eslint/return-await",
      "@typescript-eslint/use-unknown-in-catch-callback-variable",
      "@typescript-eslint/consistent-type-imports",
      "@typescript-eslint/explicit-member-accessibility",
      "@typescript-eslint/member-ordering",
      "@typescript-eslint/no-non-null-assertion",
      "@typescript-eslint/no-restricted-types",
    ],
  },
  {
    "name": "opencover/stylistic/setup",
    "plugins": [
      "stylistic",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "opencover/stylistic/rules",
    "rules": [
      "stylistic/padding-line-between-statements",
    ],
  },
  {
    "name": "opencover/unicorn/setup",
    "plugins": [
      "unicorn",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "opencover/unicorn/rules",
    "rules": [
      "unicorn/no-array-callback-reference",
      "unicorn/filename-case",
    ],
  },
  {
    "name": "opencover/test/setup",
    "plugins": [
      "vitest",
    ],
  },
  {
    "files": [
      "**/__tests__/**",
      "**/*.spec.?([cm])[jt]s?(x)",
      "**/*.test.?([cm])[jt]s?(x)",
      "**/tests/**",
    ],
    "languageOptions": {},
    "name": "opencover/test/rules",
    "rules": [
      "vitest/expect-expect",
      "vitest/no-conditional-expect",
      "vitest/no-disabled-tests",
      "vitest/no-focused-tests",
      "vitest/no-commented-out-tests",
      "vitest/no-identical-title",
      "vitest/no-import-node-test",
      "vitest/no-interpolation-in-snapshots",
      "vitest/no-mocks-import",
      "vitest/no-standalone-expect",
      "vitest/no-unneeded-async-expect-function",
      "vitest/prefer-called-exactly-once-with",
      "vitest/require-local-test-context-for-concurrent-snapshots",
      "vitest/valid-describe-callback",
      "vitest/valid-expect",
      "vitest/valid-expect-in-promise",
      "vitest/valid-title",
      "- @typescript-eslint/no-unsafe-assignment",
      "vitest/padding-around-before-all-blocks",
      "vitest/padding-around-describe-blocks",
      "vitest/padding-around-before-each-blocks",
      "vitest/padding-around-after-all-blocks",
      "vitest/padding-around-after-each-blocks",
      "vitest/padding-around-test-blocks",
    ],
    "settings": {
      "vitest": {
        "typecheck": true,
      },
    },
  },
]