[
  "<ignored>",
  {
    "ignores": [
      "**/node_modules",
      "**/dist",
      "**/.dist",
      "**/coverage",
      "**/build",
      "**/.git",
      "**/.cache",
      "**/.nuxt",
      "**/.next",
      "**/.vercel",
      "**/.changeset",
      "**/.idea",
      "**/.output",
      "**/.vitepress/cache",
      "**/.vscode",
      "**/__snapshots__",
      "**/package-lock.json",
      "**/yarn.lock",
      "**/pnpm-lock.yaml",
      "**/bun.lockb",
      "**/CHANGELOG*.md",
      "**/*.min.*",
      "**/LICENSE*",
      "**/__fixtures__",
      "**/fixtures/**",
    ],
    "name": "globalIgnores 2",
  },
  "<ignored>",
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "opencover/javascript/rules",
    "rules": [
      "constructor-super",
      "for-direction",
      "getter-return",
      "no-async-promise-executor",
      "no-case-declarations",
      "no-class-assign",
      "no-compare-neg-zero",
      "no-cond-assign",
      "no-const-assign",
      "no-constant-binary-expression",
      "no-constant-condition",
      "no-control-regex",
      "no-debugger",
      "no-delete-var",
      "no-dupe-args",
      "no-dupe-class-members",
      "no-dupe-else-if",
      "no-dupe-keys",
      "no-duplicate-case",
      "no-empty",
      "no-empty-character-class",
      "no-empty-pattern",
      "no-empty-static-block",
      "no-ex-assign",
      "no-extra-boolean-cast",
      "no-fallthrough",
      "no-func-assign",
      "no-global-assign",
      "no-import-assign",
      "no-invalid-regexp",
      "no-irregular-whitespace",
      "no-loss-of-precision",
      "no-misleading-character-class",
      "no-new-native-nonconstructor",
      "no-nonoctal-decimal-escape",
      "no-obj-calls",
      "no-octal",
      "no-prototype-builtins",
      "no-redeclare",
      "no-regex-spaces",
      "no-self-assign",
      "no-setter-return",
      "no-shadow-restricted-names",
      "no-sparse-arrays",
      "no-this-before-super",
      "no-undef",
      "no-unexpected-multiline",
      "no-unreachable",
      "no-unsafe-finally",
      "no-unsafe-negation",
      "no-unsafe-optional-chaining",
      "no-unused-labels",
      "no-unused-private-class-members",
      "no-unused-vars",
      "no-useless-backreference",
      "no-useless-catch",
      "no-useless-escape",
      "no-with",
      "require-yield",
      "use-isnan",
      "valid-typeof",
      "block-spacing",
      "capitalized-comments",
      "comma-spacing",
      "key-spacing",
      "keyword-spacing",
      "no-console",
      "no-multi-spaces",
      "no-multiple-empty-lines",
      "no-restricted-syntax",
      "no-unneeded-ternary",
      "no-use-before-define",
      "object-curly-spacing",
      "quote-props",
      "quotes",
      "semi",
      "space-before-blocks",
      "space-in-parens",
      "space-infix-ops",
      "spaced-comment",
      "lines-between-class-members",
    ],
  },
  {
    "name": "opencover/stylistic/setup",
    "plugins": [
      "stylistic",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "opencover/stylistic/rules",
    "rules": [
      "stylistic/padding-line-between-statements",
    ],
  },
  {
    "name": "opencover/imports/setup",
    "plugins": [
      "import",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "opencover/imports/rules",
    "rules": [
      "import/order",
      "- import/prefer-default-export",
    ],
  },
  {
    "name": "opencover/unicorn/setup",
    "plugins": [
      "unicorn",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "opencover/unicorn/rules",
    "rules": [
      "unicorn/no-array-callback-reference",
      "unicorn/filename-case",
    ],
  },
  {
    "name": "opencover/test/setup",
    "plugins": [
      "vitest",
    ],
  },
  {
    "files": [
      "**/__tests__/**",
      "**/*.spec.?([cm])[jt]s?(x)",
      "**/*.test.?([cm])[jt]s?(x)",
      "**/tests/**",
    ],
    "languageOptions": {},
    "name": "opencover/test/rules",
    "rules": [
      "vitest/expect-expect",
      "vitest/no-conditional-expect",
      "vitest/no-disabled-tests",
      "vitest/no-focused-tests",
      "vitest/no-commented-out-tests",
      "vitest/no-identical-title",
      "vitest/no-import-node-test",
      "vitest/no-interpolation-in-snapshots",
      "vitest/no-mocks-import",
      "vitest/no-standalone-expect",
      "vitest/no-unneeded-async-expect-function",
      "vitest/prefer-called-exactly-once-with",
      "vitest/require-local-test-context-for-concurrent-snapshots",
      "vitest/valid-describe-callback",
      "vitest/valid-expect",
      "vitest/valid-expect-in-promise",
      "vitest/valid-title",
      "- @typescript-eslint/no-unsafe-assignment",
      "vitest/padding-around-before-all-blocks",
      "vitest/padding-around-describe-blocks",
      "vitest/padding-around-before-each-blocks",
      "vitest/padding-around-after-all-blocks",
      "vitest/padding-around-after-each-blocks",
      "vitest/padding-around-test-blocks",
    ],
    "settings": {
      "vitest": {
        "typecheck": true,
      },
    },
  },
  {
    "name": "opencover/react/setup",
    "plugins": [
      "react",
      "react-hooks",
    ],
  },
  {
    "files": [
      "**/*.?([cm])jsx",
      "**/*.?([cm])tsx",
    ],
    "languageOptions": {
      "parserOptions": {
        "ecmaFeatures": {
          "jsx": true,
        },
        "ecmaVersion": 2024,
        "sourceType": "module",
      },
    },
    "name": "opencover/react/rules",
    "rules": [
      "react/display-name",
      "react/jsx-key",
      "react/jsx-no-comment-textnodes",
      "react/jsx-no-duplicate-props",
      "react/jsx-no-target-blank",
      "react/jsx-no-undef",
      "- react/jsx-uses-react",
      "react/jsx-uses-vars",
      "react/no-children-prop",
      "react/no-danger-with-children",
      "react/no-deprecated",
      "react/no-direct-mutation-state",
      "react/no-find-dom-node",
      "react/no-is-mounted",
      "react/no-render-return-value",
      "react/no-string-refs",
      "react/no-unescaped-entities",
      "react/no-unknown-property",
      "- react/no-unsafe",
      "react/prop-types",
      "- react/react-in-jsx-scope",
      "react/require-render-return",
      "react-hooks/rules-of-hooks",
      "react-hooks/exhaustive-deps",
      "react-hooks/static-components",
      "react-hooks/use-memo",
      "react-hooks/component-hook-factories",
      "react-hooks/preserve-manual-memoization",
      "react-hooks/incompatible-library",
      "react-hooks/immutability",
      "react-hooks/globals",
      "react-hooks/refs",
      "react-hooks/set-state-in-effect",
      "react-hooks/error-boundaries",
      "react-hooks/purity",
      "react-hooks/set-state-in-render",
      "react-hooks/unsupported-syntax",
      "react-hooks/config",
      "react-hooks/gating",
    ],
    "settings": {
      "react": {
        "version": "detect",
      },
    },
  },
]