export const GLOB_TEST = [
    '**/*.test.ts',
    '**/*.test.tsx',
    '**/*.test.js',
    '**/*.test.jsx',
    '**/*.spec.ts',
    '**/*.spec.tsx',
    '**/*.spec.js',
    '**/*.spec.jsx',
];

export const GLOB_EXCLUDE = [
    '**/dist',
    '**/.dist',
    '**/coverage',
    '**/build',
    '**/.cache',
    '**/.nuxt',
    '**/.next',
    '**/.vercel',
    '**/.changeset',
    '**/.idea',
    '**/.output',
    '**/.vitepress/cache',
    '**/.vscode',
    '**/__snapshots__',
    '**/*.min.*',
    '**/__fixtures__',
    '**/fixtures/**',
];
