name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: 🔎 Show Node and npm versions
        run: |
          node -v
          npm -v
          pnpm -v

      - name: 📥 Install deps
        run: pnpm install --frozen-lockfile

      - name: 🔑 Set npm auth
        run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: 🚀 Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version
          publish: pnpm changeset:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Prevent typescript-eslint from inferring a singleRun on CI to create an isolated TS program with default TS config breaking some tests,
          # see https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/typescript-estree/src/parseSettings/inferSingleRun.ts#L36
          TSESTREE_SINGLE_RUN: false
